apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - grafana-splitwise-kafka-dashboard.yaml
  - kafka-alert-rules.yaml
  - argocd-servicemonitor.yaml
