apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: splitwise-kafka-exporter
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: splitwise-kafka
      app.kubernetes.io/component: kafka-exporter
  podMetricsEndpoints:
    - targetPort: 9404
      path: /metrics
      interval: 30s
