apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: splitwise-producer
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: splitwise-export
      app.kubernetes.io/component: producer
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
