# Argo CD Application that installs Prometheus and Grafana for local observability.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: local-platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.13.3
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/Environment/local/argocd/values/monitoring-values.yaml
    - repoURL: https://github.com/yarinago/K8S-Argo-Karpenter-Kafka-GithubAction.git
      targetRevision: feature/create-kafka
      ref: values
    - repoURL: https://github.com/yarinago/K8S-Argo-Karpenter-Kafka-GithubAction.git
      targetRevision: feature/create-kafka
      path: Environment/local/argocd/apps/platform/monitoring-extra
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
