apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-local-access
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/app: http://argocd-local-access.localtest.me:8080
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/yarinago/K8S-Argo-Karpenter-Kafka-GithubAction.git
    targetRevision: feature/create-argocd
    path: Environment/local/access/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
