apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splitwise-household-expenses
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/app: http://splitwise.localtest.me:8080
spec:
  project: splitwise-household-expenses
  source:
    repoURL: https://github.com/yarinago/splitwise-household-expenses.git
    targetRevision: feature/shift_to_k8s
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: splitwise-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
