apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splitwise-local-access
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/yarinago/K8S-Argo-Karpenter-Kafka-GithubAction.git
    targetRevision: feature/create-argocd
    path: Environment/local/access/splitwise
  destination:
    server: https://kubernetes.default.svc
    namespace: splitwise-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
