deployment:
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesIngress:
    publishedService:
      enabled: false

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  enabled: false

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
